# Setup
title:               NotAlfred Blog
tagline:             'Human Shenanigans'
url:                 http://thisnotalfred.github.io/blog
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo